// Disclaimer.js
import React from "react";
import "../css/disclaimer.css"

const Disclaimer = () => {
  return (
    <div className="disclaimer-container">
    <header className="disclaimer-header">
      <h1>Disclaimer</h1>
    </header>
    <section className="disclaimer-section">
      <ul>
        <li>
          <strong>Purpose and Accuracy:</strong>
          <p>
            This website, Udyam Uplift, provides psychometric tests and related content for informational purposes only. The information and reports generated by our services are curated by experts to depict personality traits with a high degree of accuracy. However, it is important to note that no personality assessment tool can guarantee 100% accuracy.
          </p>
        </li>
        <li>
          <strong>User Responsibilities:</strong>
          <p>
            Users are encouraged to take the psychometric tests on their own and provide truthful responses. The accuracy of the results is greatly dependent on the honesty and accuracy of user input. Udyam Uplift is not responsible for any decisions or actions taken based on the information provided on this website.
          </p>
        </li>
        <li>
          <strong>Legal Protection:</strong>
          <p>
            This disclaimer is provided for legal protection and to inform users about the limitations of our services. Udyam Uplift is not responsible for any decisions or actions taken based on the information provided on this website.
          </p>
        </li>
        <li>
          <strong>Contact Information:</strong>
          <p>
            If you have any questions or concerns regarding this disclaimer or our services, please contact us at{" "}
            <a href="mailto:udyamuplift@gmail.com">udyamuplift@gmail.com</a>.
          </p>
        </li>
      </ul>
    </section>
  </div>
  );
};

export default Disclaimer;
